/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keeper;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author happyhappyyay
 */
public class TimeKeeper extends javax.swing.JFrame {
    private Calendar cal;

    private final String TITLE = "Time Keeper";
    private final String TIME_IN = "Time-in";
    private final String TIME_OUT= "Time-out";
    static final String DATE_FORMAT = "MMMM dd, yyyy";
    static final String TIME_FORMAT = "hh:mm a";

    /**
     * Creates new form TimeKeeper
     */
    public TimeKeeper() {
        initComponents();
        initInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        dateLabel = new javax.swing.JLabel();
        inLabel = new javax.swing.JLabel();
        outLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        weekLabel = new javax.swing.JLabel();
        hourLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.pink);

        startButton.setText("START");
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startButtonMouseClicked(evt);
            }
        });

        finishButton.setText("FINISH");
        finishButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                finishButtonMouseClicked(evt);
            }
        });

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dateLabel.setText("Date");

        inLabel.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        inLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inLabel.setText("Time-in");
        inLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        outLabel.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        outLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outLabel.setText("Time-out");
        outLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        weekLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        weekLabel.setText("week");

        hourLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hourLabel.setText("hours");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(weekLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(outLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finishButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hourLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(dateLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekLabel)
                    .addComponent(hourLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outLabel)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initInfo() {
        this.setTitle(TITLE);
        DateFormat format = new SimpleDateFormat(DATE_FORMAT);
        resetCalendar();
        cal.set(Calendar.DAY_OF_WEEK, cal.getFirstDayOfWeek());
        weekLabel.setText(format.format(cal.getTime()));
        updateFileRelatedInformation();
    }

    private void startButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseClicked
        resetCalendar();
        DateFormat dayFormat = new SimpleDateFormat(DATE_FORMAT);
        String instanceDate = dayFormat.format(cal.getTime());
        String createNewInstance = "Create a new instance of " + instanceDate+"?";
        if (inLabel.getText().equals(TIME_IN)) {
            long time = System.currentTimeMillis();
            DateFormat format = new SimpleDateFormat(TIME_FORMAT);
            Date date = new Date(time);
            inLabel.setText(format.format(date));
            WriteFile.write(cal.getTimeInMillis(), time, true);
            updateFileRelatedInformation();
        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, createNewInstance, "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                long time = System.currentTimeMillis();
                DateFormat format = new SimpleDateFormat(TIME_FORMAT);
                Date date = new Date(time);
                inLabel.setText(format.format(date));
                outLabel.setText(TIME_OUT);
                WriteFile.write(cal.getTimeInMillis(), time, true);
                updateFileRelatedInformation();
            }
        }
    }//GEN-LAST:event_startButtonMouseClicked

    private void finishButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finishButtonMouseClicked
        long time = System.currentTimeMillis();
        DateFormat format = new SimpleDateFormat(TIME_FORMAT);
        Date date = new Date(System.currentTimeMillis());
        outLabel.setText(format.format(date));
        resetCalendar();
        WriteFile.convertWrite(dateLabel.getText(), cal.getTimeInMillis(),time);
        updateFileRelatedInformation();
    }//GEN-LAST:event_finishButtonMouseClicked

    private void resetCalendar() {
        cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.clear(Calendar.MINUTE);
        cal.clear(Calendar.SECOND);
        cal.clear(Calendar.MILLISECOND);
    }

    private void updateFileRelatedInformation() {
        final int START_POSITION = 0;
        Date date = new Date(System.currentTimeMillis());
        DateFormat format = new SimpleDateFormat(TIME_FORMAT);
        ReadFile readFile = new ReadFile();
        String[] log = readFile.getLog();
        jTextArea1.setText(FileAssessor.returnFormattedFile(log));
        resetCalendar();
        long day = cal.getTimeInMillis();
        cal.set(Calendar.DAY_OF_WEEK, cal.getFirstDayOfWeek());
        long week = cal.getTimeInMillis();
        hourLabel.setText(String.format(Locale.US, "%.2f hrs", FileAssessor.calculateWeekHours(log, week)));
        long[] times = FileAssessor.retrieveTime(log, day);
        DateFormat formatD = new SimpleDateFormat(DATE_FORMAT);
        switch (times.length) {
            case 0:
                break;
            case 1:
                date = new Date(times[0]);
                inLabel.setText(format.format(date));
                break;
            case 2:
                date = new Date(times[1]);
                outLabel.setText(format.format(date));
                date = new Date(times[0]);
                inLabel.setText(format.format(date));
                break;
        }
        dateLabel.setText(formatD.format(date));
        jTextArea1.setCaretPosition(START_POSITION);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimeKeeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TimeKeeper().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel hourLabel;
    private javax.swing.JLabel inLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel outLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel weekLabel;
    // End of variables declaration//GEN-END:variables
}
